### ISSUE TITLE
Inclusão de gitignore

### ISSUE THREAD

**Issue by deniojunior** [idvogadosorg/infra#3]
## Resumo

É necessário incluir um `.gitignore` para evitar que arquivos indesejados sejam commitados. Inicialmente, podemos ignorar apenas os arquivos de IDEs comuns. A adição de demais itens podem ser feita de forma incremental, conforme o crescimento do projeto.

## Requisitos
- Não poluir o .gitignore com a listagem de itens desnecessários

**Comment by pabrrs** [comment]
Como a PR #4 já foi mergeada, vale fechar essa issue ?
